const recipes=[
 {name:'Krämig tomatpasta',icon:'🍝',protein:'vegetariskt',time:'20 min',price:31,ingredients:['spaghetti 250 g','krossade tomater 1 fp','matlagningsgrädde 2 dl','gul lök 1 st','parmesan'],steps:['Koka pastan enligt förpackningen.','Fräs hackad lök mjuk i olja.','Rör i tomater och grädde, låt sjuda 10 minuter.','Vänd ner pastan och toppa med parmesan.']},
 {name:'Ugnsbakad lax med potatis',icon:'🐟',protein:'fisk',time:'35 min',price:62,ingredients:['laxfilé 250 g','potatis 500 g','crème fraiche 2 dl','citron 1 st','broccoli 1 st'],steps:['Sätt ugnen på 200°.','Rosta potatis i klyftor 25 minuter.','Lägg laxen bredvid och baka ytterligare 12–15 minuter.','Servera med broccoli, citron och crème fraiche.']},
 {name:'Torsk med citronris',icon:'🐟',protein:'fisk',time:'30 min',price:51,ingredients:['torskfilé 250 g','ris 2 dl','citron 1 st','gröna ärtor 250 g','smör'],steps:['Koka riset.','Stek eller baka torsken tills den faller isär.','Värm ärtorna.','Servera med citronsaft och en klick smör.']},
 {name:'Fiskgratäng med dill',icon:'🐠',protein:'fisk',time:'40 min',price:58,ingredients:['vit fisk 300 g','potatis 500 g','matlagningsgrädde 2 dl','dill','citron 1 st'],steps:['Sätt ugnen på 200° och koka potatisen.','Lägg fisken i en form.','Häll över grädde, dill och citron.','Gratinera 20 minuter och servera med potatis.']},
 {name:'Laxpasta med spenat',icon:'🍝',protein:'fisk',time:'25 min',price:59,ingredients:['laxfilé 250 g','pasta 250 g','matlagningsgrädde 2 dl','spenat 1 påse','citron 1 st'],steps:['Koka pastan.','Stek laxen i bitar.','Tillsätt grädde och spenat.','Vänd ner pasta och smaka av med citron.']},
 {name:'Panerad fisk med kall sås',icon:'🐟',protein:'fisk',time:'25 min',price:43,ingredients:['fiskpinnar 1 fp','potatis 500 g','gröna ärtor 250 g','crème fraiche 2 dl','citron 1 st'],steps:['Rosta potatisen i ugnen.','Tillaga fiskpinnarna enligt förpackningen.','Blanda crème fraiche med citron.','Servera med ärtor och kall sås.']},
 {name:'Vegetarisk chili',icon:'🫘',protein:'vegetariskt',time:'30 min',price:27,ingredients:['kidneybönor 1 burk','krossade tomater 1 fp','majs 1 burk','paprika 1 st','ris 2 dl'],steps:['Koka riset.','Fräs paprika i en kastrull.','Tillsätt tomater, avrunna bönor och majs.','Låt sjuda 15 minuter och servera med ris.']},
 {name:'Kycklingwok med nudlar',icon:'🥢',protein:'kyckling',time:'25 min',price:49,ingredients:['kycklingfilé 250 g','äggnudlar 1 fp','wokgrönsaker 1 fp','soja','lime 1 st'],steps:['Koka nudlarna.','Strimla och stek kycklingen ordentligt.','Tillsätt grönsaker och woka några minuter.','Vänd ner nudlar, soja och lime.']},
 {name:'Kyckling i pestosås',icon:'🍗',protein:'kyckling',time:'30 min',price:55,ingredients:['kycklingfilé 250 g','pasta 250 g','pesto 1 burk','matlagningsgrädde 2 dl','körsbärstomater'],steps:['Koka pastan.','Stek kycklingen i bitar.','Rör i pesto och grädde.','Vänd ner pasta och tomater.']},
 {name:'Kycklingtacos',icon:'🌮',protein:'kyckling',time:'25 min',price:52,ingredients:['kycklingfilé 250 g','tortillabröd 1 fp','tacokrydda','tomat 2 st','majs 1 burk'],steps:['Strimla och stek kycklingen med tacokrydda.','Hacka tomater och häll av majsen.','Värm tortillas.','Fyll och servera.']},
 {name:'Kycklinggryta med curry',icon:'🥘',protein:'kyckling',time:'30 min',price:48,ingredients:['kycklingfilé 250 g','ris 2 dl','kokosmjölk 1 burk','curry','paprika 1 st'],steps:['Koka riset.','Stek kyckling och paprika.','Tillsätt curry och kokosmjölk.','Låt sjuda 10 minuter och servera med ris.']},
 {name:'Kycklingburgare med ugnspotatis',icon:'🍔',protein:'kyckling',time:'35 min',price:53,ingredients:['kycklingburgare 2 st','hamburgerbröd 2 st','potatis 500 g','sallad','tomat 1 st'],steps:['Rosta potatisklyftor i ugnen.','Stek burgarna genom.','Rosta bröden lätt.','Bygg burgare med sallad och tomat.']},
 {name:'Halloumitacos',icon:'🌮',protein:'vegetariskt',time:'25 min',price:44,ingredients:['halloumi 200 g','tortillabröd 1 fp','svarta bönor 1 burk','tomat 2 st','avokado 1 st'],steps:['Stek tärnad halloumi gyllene.','Värm bönorna med lite kryddor.','Hacka tomat och avokado.','Fyll varma tortillas och servera.']},
 {name:'Linsbolognese',icon:'🍅',protein:'vegetariskt',time:'30 min',price:24,ingredients:['röda linser 1,5 dl','spaghetti 250 g','krossade tomater 1 fp','morot 1 st','gul lök 1 st'],steps:['Koka pastan.','Fräs riven morot och hackad lök.','Häll i tomater och linser.','Låt sjuda 15 minuter och servera med pastan.']},
 {name:'Köttfärssås med spaghetti',icon:'🍝',protein:'nöt',time:'30 min',price:46,ingredients:['nötfärs 250 g','spaghetti 250 g','krossade tomater 1 fp','morot 1 st','gul lök 1 st'],steps:['Koka pastan.','Stek färsen och tillsätt hackad lök och riven morot.','Rör i tomater och låt sjuda 15 minuter.','Smaka av och servera.']},
 {name:'Biffstroganoff med ris',icon:'🥘',protein:'nöt',time:'30 min',price:54,ingredients:['strimlad nötfärs 250 g','ris 2 dl','matlagningsgrädde 2 dl','tomatpuré','gul lök 1 st'],steps:['Koka riset.','Stek köttet och löken.','Rör i tomatpuré och grädde.','Låt sjuda några minuter och servera.']},
 {name:'Nötfärstacos',icon:'🌮',protein:'nöt',time:'25 min',price:47,ingredients:['nötfärs 250 g','tortillabröd 1 fp','tacokrydda','tomat 2 st','majs 1 burk'],steps:['Stek färsen och tillsätt krydda.','Hacka tomater och häll av majsen.','Värm tortillas.','Fyll och servera.']},
 {name:'Färsbiffar med bulgur',icon:'🥩',protein:'nöt',time:'35 min',price:52,ingredients:['nötfärs 250 g','bulgur 2 dl','ägg 1 st','morot 2 st','yoghurt 2 dl'],steps:['Koka bulgur.','Blanda färs med ägg och forma biffar.','Stek biffarna genom.','Rosta morötter och servera med yoghurt.']},
 {name:'Chili con carne',icon:'🫘',protein:'nöt',time:'35 min',price:45,ingredients:['nötfärs 250 g','kidneybönor 1 burk','krossade tomater 1 fp','ris 2 dl','gul lök 1 st'],steps:['Koka riset.','Stek färs och lök.','Tillsätt tomater och bönor.','Låt sjuda 20 minuter och servera.']},
 {name:'Tortillapizza med grönsaker',icon:'🍕',protein:'vegetariskt',time:'20 min',price:29,ingredients:['tortillabröd 1 fp','tomatsås','riven ost 150 g','paprika 1 st','champinjoner 1 fp'],steps:['Sätt ugnen på 225°.','Bred tomatsås på tortillabröden.','Toppa med ost och grönsaker.','Grädda 7–9 minuter.']},
 {name:'Currygryta med kikärter',icon:'🥘',protein:'vegetariskt',time:'25 min',price:26,ingredients:['kikärter 1 burk','kokosmjölk 1 burk','curry','ris 2 dl','spenat 1 påse'],steps:['Koka riset.','Fräs curryn kort i olja.','Tillsätt kokosmjölk och kikärter.','Vänd ner spenat och servera med ris.']},
 {name:'Fläskfärsbiffar med klyftpotatis',icon:'🥔',protein:'fläsk',time:'40 min',price:42,ingredients:['fläskfärs 250 g','potatis 500 g','ägg 1 st','gul lök 1 st','lingonsylt'],steps:['Sätt ugnen på 225° och rosta potatisklyftor 30 minuter.','Blanda färs, ägg och finhackad lök.','Forma små biffar och stek dem genom.','Servera med potatis och lingon.']}
 ,{name:'Korvstroganoff med ris',icon:'🌭',protein:'fläsk',time:'25 min',price:35,ingredients:['falukorv 300 g','ris 2 dl','matlagningsgrädde 2 dl','tomatpuré','gul lök 1 st'],steps:['Koka riset.','Stek strimlad korv och lök.','Rör i tomatpuré och grädde.','Låt sjuda kort och servera.']}
 ,{name:'Fläskkotlett med rostad potatis',icon:'🥩',protein:'fläsk',time:'35 min',price:56,ingredients:['fläskkotlett 300 g','potatis 500 g','broccoli 1 st','crème fraiche 2 dl','citron 1 st'],steps:['Rosta potatisklyftor i ugnen.','Stek kotletterna genom.','Koka eller ånga broccoli.','Servera med citroncrème fraiche.']}
 ,{name:'Pastagratäng med bacon',icon:'🥓',protein:'fläsk',time:'35 min',price:44,ingredients:['bacon 1 fp','pasta 250 g','matlagningsgrädde 2 dl','riven ost 150 g','broccoli 1 st'],steps:['Koka pastan.','Stek bacon och broccoli.','Blanda med pasta och grädde i en form.','Toppa med ost och gratinera 15 minuter.']}
 ,{name:'Pulled pork-tacos',icon:'🌮',protein:'fläsk',time:'30 min',price:50,ingredients:['pulled pork 1 fp','tortillabröd 1 fp','coleslaw 1 fp','tomat 2 st','majs 1 burk'],steps:['Värm pulled pork enligt förpackningen.','Hacka tomater och häll av majsen.','Värm tortillas.','Fyll med pulled pork och coleslaw.']}
];
const moreRecipes=[
 ['Citronsej med couscous','fisk',48,'🐟',['sejfilé 250 g','couscous 2 dl','citron 1 st','haricots verts 250 g']],['Rödspätta med dillpotatis','fisk',57,'🐟',['rödspätta 250 g','potatis 500 g','dill','citron 1 st']],['Tonfiskpasta','fisk',39,'🐟',['tonfisk 1 burk','pasta 250 g','krossade tomater 1 fp','gul lök 1 st']],['Fiskburgare med coleslaw','fisk',53,'🍔',['fiskburgare 2 st','hamburgerbröd 2 st','coleslaw 1 fp','potatis 500 g']],['Cajunlax med bulgur','fisk',64,'🐟',['laxfilé 250 g','bulgur 2 dl','paprika 1 st','crème fraiche 2 dl']],['Torsk tacos','fisk',49,'🌮',['torskfilé 250 g','tortillabröd 1 fp','avokado 1 st','tomat 2 st']],['Asiatisk lax med ris','fisk',63,'🥢',['laxfilé 250 g','ris 2 dl','broccoli 1 st','soja']],['Fiskgryta med saffran','fisk',67,'🥘',['vit fisk 250 g','potatis 500 g','matlagningsgrädde 2 dl','saffran']],['Makaroner med tonfiskröra','fisk',34,'🍝',['tonfisk 1 burk','makaroner 250 g','crème fraiche 2 dl','majs 1 burk']],['Lax med pestopotatis','fisk',66,'🐟',['laxfilé 250 g','potatis 500 g','pesto 1 burk','sallad 1 påse']],
 ['Kycklingpasta med citron','kyckling',51,'🍝',['kycklingfilé 250 g','pasta 250 g','citron 1 st','matlagningsgrädde 2 dl']],['Teriyakikyckling med ris','kyckling',50,'🥢',['kycklingfilé 250 g','ris 2 dl','broccoli 1 st','teriyakisås']],['Kycklingfajitas','kyckling',54,'🌮',['kycklingfilé 250 g','tortillabröd 1 fp','paprika 2 st','fajitakrydda']],['Kyckling med rostad sötpotatis','kyckling',58,'🍗',['kycklingfilé 250 g','sötpotatis 500 g','yoghurt 2 dl','sallad 1 påse']],['Kyckling Caesar-wrap','kyckling',56,'🌯',['kycklingfilé 250 g','tortillabröd 1 fp','romansallad 1 st','caesardressing']],['Kyckling i tomatsås','kyckling',47,'🥘',['kycklingfilé 250 g','ris 2 dl','krossade tomater 1 fp','paprika 1 st']],['Kycklingschnitzel med klyftpotatis','kyckling',55,'🍗',['kycklingschnitzel 2 st','potatis 500 g','ärtor 250 g','citron 1 st']],['Kyckling- och halloumispett','kyckling',61,'🍢',['kycklingfilé 250 g','halloumi 200 g','bulgur 2 dl','paprika 1 st']],['Kycklingrisoni med fetaost','kyckling',57,'🍝',['kycklingfilé 250 g','risoni 250 g','fetaost 150 g','spenat 1 påse']],['Honungskyckling med nudlar','kyckling',52,'🥢',['kycklingfilé 250 g','äggnudlar 1 fp','morot 2 st','honung']],
 ['Hamburgare med ugnsfries','nöt',59,'🍔',['nötfärsburgare 2 st','hamburgerbröd 2 st','potatis 500 g','sallad 1 påse']],['Lasagne med färs','nöt',55,'🍝',['nötfärs 250 g','lasagneplattor 1 fp','krossade tomater 1 fp','riven ost 150 g']],['Färsfyllda paprikor','nöt',50,'🫑',['nötfärs 250 g','paprika 2 st','ris 2 dl','krossade tomater 1 fp']],['Nötfärswok med nudlar','nöt',48,'🥢',['nötfärs 250 g','äggnudlar 1 fp','wokgrönsaker 1 fp','soja']],['Kebabfärs med bulgur','nöt',52,'🥙',['nötfärs 250 g','bulgur 2 dl','yoghurt 2 dl','tomat 2 st']],['Mexikansk färspaj','nöt',58,'🥧',['nötfärs 250 g','pajdeg 1 fp','majs 1 burk','riven ost 150 g']],['Färsgryta med potatis','nöt',49,'🥘',['nötfärs 250 g','potatis 500 g','matlagningsgrädde 2 dl','morot 2 st']],['Bolognese med linser','nöt',43,'🍝',['nötfärs 200 g','röda linser 1 dl','spaghetti 250 g','krossade tomater 1 fp']],['Färsbiffar med tzatziki','nöt',54,'🥩',['nötfärs 250 g','potatis 500 g','yoghurt 2 dl','gurka 1 st']],['Nötfärsquesadillas','nöt',48,'🌮',['nötfärs 250 g','tortillabröd 1 fp','riven ost 150 g','salsa 1 burk']],
 ['Pasta carbonara','fläsk',39,'🥓',['bacon 1 fp','pasta 250 g','ägg 2 st','parmesan']],['Fläskpannkaka med lingon','fläsk',36,'🥞',['rimmat fläsk 250 g','ägg 3 st','mjölk 5 dl','lingonsylt']],['Kasslergratäng med ris','fläsk',48,'🥘',['kassler 300 g','ris 2 dl','matlagningsgrädde 2 dl','ananas 1 burk']],['Chorizopasta','fläsk',42,'🍝',['chorizo 250 g','pasta 250 g','krossade tomater 1 fp','gul lök 1 st']],['Fläskfilé med pasta','fläsk',65,'🥩',['fläskfilé 300 g','pasta 250 g','champinjoner 1 fp','matlagningsgrädde 2 dl']],['Korv med potatismos','fläsk',33,'🌭',['falukorv 300 g','potatis 500 g','mjölk 2 dl','morot 2 st']],['Skink- och ostpaj','fläsk',45,'🥧',['rökt skinka 200 g','pajdeg 1 fp','ägg 3 st','riven ost 150 g']],['Fläskfärswok med ris','fläsk',43,'🥢',['fläskfärs 250 g','ris 2 dl','wokgrönsaker 1 fp','soja']],['Salsicciapasta','fläsk',51,'🍝',['salsiccia 250 g','pasta 250 g','tomatsås 1 fp','spenat 1 påse']],['Kryddiga fläskfärstacos','fläsk',44,'🌮',['fläskfärs 250 g','tortillabröd 1 fp','tacokrydda','majs 1 burk']],
 ['Svamprisotto','vegetariskt',38,'🍚',['risottoris 2 dl','champinjoner 1 fp','parmesan','gul lök 1 st']],['Vegetarisk lasagne','vegetariskt',40,'🍝',['lasagneplattor 1 fp','krossade tomater 1 fp','spenat 1 påse','riven ost 150 g']],['Falafel med couscous','vegetariskt',35,'🧆',['falafel 1 fp','couscous 2 dl','yoghurt 2 dl','tomat 2 st']],['Broccolipasta','vegetariskt',32,'🥦',['pasta 250 g','broccoli 1 st','matlagningsgrädde 2 dl','parmesan']],['Vegetarisk pytt','vegetariskt',31,'🥔',['potatis 500 g','morot 2 st','ägg 2 st','rödbetor 1 burk']],['Auberginegryta med ris','vegetariskt',37,'🥘',['aubergine 1 st','ris 2 dl','krossade tomater 1 fp','kikärter 1 burk']],['Quesadillas med bönor','vegetariskt',36,'🌮',['tortillabröd 1 fp','svarta bönor 1 burk','riven ost 150 g','salsa 1 burk']],['Vegobullar med mos','vegetariskt',40,'🥔',['vegobullar 1 fp','potatis 500 g','mjölk 2 dl','lingonsylt']],['Gnocchi med pesto','vegetariskt',41,'🍝',['gnocchi 1 fp','pesto 1 burk','körsbärstomater','fetaost 150 g']],['Soppa med rostade kikärter','vegetariskt',29,'🍲',['morot 4 st','kikärter 1 burk','buljong','bröd 1 fp']]
];
const genericSteps={fisk:['Förbered tillbehören enligt ingredienslistan.','Tillaga fisken i panna eller ugn tills den är genomlagad.','Smaka av och servera genast.'],kyckling:['Förbered tillbehören enligt ingredienslistan.','Tillaga kycklingen tills den är helt genomlagad.','Blanda ihop rätten och servera varmt.'],nöt:['Förbered tillbehören enligt ingredienslistan.','Stek nötfärs eller kött ordentligt.','Blanda ihop rätten och servera varmt.'],fläsk:['Förbered tillbehören enligt ingredienslistan.','Tillaga fläsket ordentligt.','Blanda ihop rätten och servera varmt.']};
genericSteps.vegetariskt=['Förbered tillbehören enligt ingredienslistan.','Tillaga grönsaker och huvudingredienser tills de är varma och mjuka.','Smaka av och servera varmt.'];
Object.assign(genericSteps,{fisk:['Börja med potatis, ris eller pasta enligt anvisningen på förpackningen.','Skölj och förbered grönsakerna. Tillaga dem så att de behåller lite spänst.','Krydda fisken med salt och peppar. Stek den på medelvärme eller baka i 200° tills den lätt delar sig.','Rör ihop såsen och smaka av med citron, salt och peppar.','Lägg upp direkt och servera medan fisken är saftig.'],kyckling:['Sätt ugnen på 200° om rätten innehåller ugnsrostade tillbehör.','Tillaga potatis, ris, pasta eller bröd enligt förpackningen.','Krydda kycklingen och stek den på medelhög värme tills den är helt genomlagad.','Tillaga grönsakerna och rör ihop eventuell sås.','Lägg upp allt på tallrikar och smaka av före servering.'],nöt:['Förbered tillbehören så att de kan bli klara samtidigt som köttet.','Skär grönsaker och förbered sås eller dressing.','Stek köttet eller färsen på hög värme i omgångar så att det får ordentligt med färg.','Sänk värmen och gör klart enligt rätten – låt större köttbitar vila ett par minuter.','Servera med tillbehören och smaka av med salt och peppar.'],fläsk:['Börja med det tillbehör som tar längst tid, till exempel potatis eller ris.','Förbered grönsaker och eventuell sås.','Tillaga fläsket på medelhög värme tills det är genomlagat och har fin yta.','Låt köttet vila kort medan du gör klart såsen och grönsakerna.','Skär upp, lägg på tallrik och servera direkt.'],vegetariskt:['Förbered tillbehören enligt anvisningen på förpackningen.','Skär grönsaker och förbered huvudråvaran.','Stek eller rosta huvudråvaran på medelhög värme tills den får fin färg och är genomvarm.','Tillaga grönsaker och rör ihop en enkel sås eller dressing.','Smaka av med salt, peppar och citron eller vinäger före servering.']});
recipes.push(...moreRecipes.map(([name,protein,price,icon,ingredients])=>({name,protein,price,icon,ingredients,time:'ca 30 min',steps:genericSteps[protein]})));
const premiumRecipes=[
 ['Halstrad lax med sparris','fisk',94,'🐟',['laxfilé 350 g','färsk sparris 250 g','färskpotatis 500 g','citron 1 st']],['Räkrisotto','fisk',88,'🦐',['räkor 300 g','risottoris 2 dl','parmesan','gul lök 1 st']],['Hälleflundra med brynt smör','fisk',108,'🐟',['hälleflundra 300 g','potatis 500 g','smör','haricots verts 250 g']],['Lax med fetaost och rostad potatis','fisk',82,'🐟',['laxfilé 300 g','fetaost 150 g','potatis 500 g','sallad 1 påse']],['Skaldjurspasta','fisk',96,'🦐',['blandade skaldjur 300 g','pasta 250 g','matlagningsgrädde 2 dl','citron 1 st']],
 ['Kyckling med parmaskinka','kyckling',82,'🍗',['kycklingfilé 300 g','parmaskinka 1 fp','potatis 500 g','sallad 1 påse']],['Kyckling med mozzarella och pesto','kyckling',78,'🍗',['kycklingfilé 300 g','mozzarella 1 fp','pesto 1 burk','pasta 250 g']],['Kyckling med svamprisotto','kyckling',86,'🍗',['kycklingfilé 300 g','risottoris 2 dl','champinjoner 1 fp','parmesan']],['Kyckling med chèvre och rödbeta','kyckling',84,'🍗',['kycklingfilé 300 g','chèvre 150 g','rödbetor 1 fp','bulgur 2 dl']],['Krispig kyckling med avokadosallad','kyckling',76,'🍗',['kycklingschnitzel 2 st','avokado 2 st','potatis 500 g','sallad 1 påse']],
 ['Entrecôte med rostad potatis','nöt',115,'🥩',['entrecôte 350 g','potatis 500 g','bearnaisesås','sallad 1 påse']],['Biffpasta med parmesan','nöt',96,'🍝',['biffstrimlor 300 g','pasta 250 g','parmesan','champinjoner 1 fp']],['Rödvinsbräserad högrev','nöt',92,'🥘',['högrev 400 g','potatis 500 g','morot 3 st','rödvinssås']],['Smashburgare med cheddar','nöt',84,'🍔',['nötfärs 350 g','hamburgerbröd 2 st','cheddar 1 fp','potatis 500 g']],['Asiatisk biff med nudlar','nöt',98,'🥢',['lövbiff 300 g','äggnudlar 1 fp','wokgrönsaker 1 fp','teriyakisås']],
 ['Fläskfilé med svampsås','fläsk',84,'🥩',['fläskfilé 350 g','potatis 500 g','champinjoner 1 fp','matlagningsgrädde 2 dl']],['Prosciuttolindad kycklingkorv','fläsk',75,'🍗',['kycklingkorv 300 g','parmaskinka 1 fp','potatis 500 g','sallad 1 påse']],['Salsiccia med burrata','fläsk',82,'🍝',['salsiccia 300 g','burrata 1 st','pasta 250 g','körsbärstomater']],['Fläskytterfilé med pepparsås','fläsk',88,'🥩',['fläskytterfilé 350 g','potatis 500 g','pepparsås','broccoli 1 st']],['Chorizo med saffransrisotto','fläsk',79,'🍚',['chorizo 300 g','risottoris 2 dl','saffran','parmesan']],
 ['Tryffelpasta med burrata','vegetariskt',76,'🍝',['pasta 250 g','burrata 1 st','tryffelolja','champinjoner 1 fp']],['Halloumi med granatäpplebulgur','vegetariskt',72,'🧀',['halloumi 300 g','bulgur 2 dl','granatäpple 1 st','avokado 1 st']],['Vegetarisk svamprisotto','vegetariskt',68,'🍚',['risottoris 2 dl','blandad svamp 300 g','parmesan','vitlök']],['Gnocchi med burrata och pesto','vegetariskt',74,'🍝',['gnocchi 1 fp','burrata 1 st','pesto 1 burk','körsbärstomater']],['Rostad blomkål med fetaost','vegetariskt',62,'🥦',['blomkål 1 st','fetaost 200 g','kikärter 1 burk','couscous 2 dl']]
];
recipes.push(...premiumRecipes.map(([name,protein,price,icon,ingredients])=>({name,protein,price,icon,ingredients,time:'ca 35 min',steps:genericSteps[protein]})));
const recipeCatalogs={
 fisk:{icon:'🐟',items:[['Torsk','torskfilé 300 g',60],['Lax','laxfilé 300 g',78],['Sej','sejfilé 300 g',52],['Kolja','koljafilé 300 g',64],['Räkor','räkor 300 g',84],['Tonfisk','tonfisk 2 burkar',42],['Rödspätta','rödspätta 300 g',71],['Havskatt','havskatt 300 g',82],['Sill','matjessill 1 fp',48],['Fiskfärs','fiskfärs 300 g',58]]},
 kyckling:{icon:'🍗',items:[['Citronkyckling','kycklingfilé 300 g',60],['Örtkyckling','kycklinglårfilé 350 g',63],['Kycklingspett','kycklingfilé 300 g',58],['Kycklingpiccata','kycklingfilé 300 g',72],['Kycklingfärs','kycklingfärs 300 g',55],['Kycklingkorv','kycklingkorv 300 g',48],['Chilikyckling','kycklingfilé 300 g',62],['Kycklinglår','kycklinglår 500 g',54],['Kyckling schnitzel','kycklingschnitzel 2 st',66],['Kycklingfärsbiffar','kycklingfärs 300 g',59]]},
 nöt:{icon:'🥩',items:[['Lövbiff','lövbiff 300 g',76],['Ryggbiff','ryggbiff 300 g',105],['Nötfärsbiffar','nötfärs 350 g',60],['Högrev','högrev 400 g',78],['Rostbiff','rostbiff 300 g',92],['Nötfärs','nötfärs 300 g',55],['Entrecôte','entrecôte 300 g',112],['Biffstrimlor','biffstrimlor 300 g',82],['Köttbullar','nötköttbullar 300 g',58],['Boeuf bourguignon','högrev 400 g',88]]},
 fläsk:{icon:'🥩',items:[['Fläskfilé','fläskfilé 350 g',78],['Fläskytterfilé','fläskytterfilé 350 g',75],['Salsiccia','salsiccia 300 g',60],['Chorizo','chorizo 300 g',50],['Kassler','kassler 350 g',48],['Fläskfärsbiffar','fläskfärs 350 g',52],['Kotlett','fläskkotlett 350 g',64],['Pulled pork','pulled pork 1 fp',56],['Falukorv','falukorv 400 g',36],['Prosciutto','parmaskinka 1 fp',70]]},
 vegetariskt:{icon:'🥬',items:[['Halloumi','halloumi 300 g',55],['Tofu','fast tofu 300 g',42],['Kikärter','kikärter 2 burkar',32],['Belugalinser','belugalinser 2 dl',34],['Svamp','blandad svamp 400 g',48],['Fetaost','fetaost 250 g',45],['Aubergine','aubergine 2 st',35],['Vegofärs','vegofärs 300 g',52],['Blomkål','blomkål 1 st',38],['Burrata','burrata 2 st',72]]}
};
const formats=[['med citronris','ris 2 dl','broccoli 1 st','citron 1 st',3],['med rostad potatis','potatis 500 g','haricots verts 250 g','crème fraiche 2 dl',6],['med krämig pasta','pasta 250 g','spenat 1 påse','matlagningsgrädde 2 dl',8]];
function generatedSteps(protein,main,side,veg,sauce){const method={fisk:'Torka av fisken. Krydda med salt och peppar och stek den på medelvärme 2–3 minuter per sida, eller baka i 200° tills fisken lätt delar sig.',kyckling:'Skär kycklingen i jämnstora bitar. Krydda med salt och peppar och stek på medelhög värme tills den är helt genomlagad och har fått fin färg.',nöt:'Krydda köttet eller färsen med salt och peppar. Stek i omgångar på hög värme så att det får ordentligt med stekyta.',fläsk:'Krydda fläsket med salt och peppar. Stek på medelhög värme tills det är genomlagat och låt vila ett par minuter.',vegetariskt:'Förbered huvudråvaran enligt förpackningen. Stek eller rosta den på medelhög värme tills den får fin färg och är genomvarm.'}[protein];return [`Börja med ${side.toLowerCase()}. Tillaga enligt förpackningen och håll varmt under lock.`,`Förbered ${veg.toLowerCase()} medan tillbehöret tillagas. ${veg.includes('spenat')?'Skölj spenaten och vänd ner den precis före servering.':'Koka, rosta eller stek grönsaken tills den är lagom mjuk.'}`,`Tillaga ${main.toLowerCase()}. ${method}`,`Rör ihop eller smaka av ${sauce.toLowerCase()}. Lägg upp tillbehör, grönsaker och huvudråvara på varma tallrikar.`,`Avsluta med att smaka av med salt, peppar och eventuellt lite syra från citron eller vinäger.`]}
recipes.push(...Object.entries(recipeCatalogs).flatMap(([protein,catalog])=>catalog.items.flatMap(([name,main,base])=>formats.map(([style,side,veg,sauce,extra])=>({name:`${name} ${style}`,protein,price:base+extra,icon:catalog.icon,ingredients:[main,side,veg,sauce],time:'ca 30 min',steps:generatedSteps(protein,main,side,veg,sauce)})))));
const proteins=['allt','fisk','kyckling','nöt','fläsk','vegetariskt'];const labels={allt:'Alla',fisk:'Fisk',kyckling:'Kyckling',nöt:'Nöt',fläsk:'Fläsk',vegetariskt:'Vegetariskt'};const $=s=>document.querySelector(s);let current=[],selected=new Set(['allt']);
function kronor(n){return `${Math.round(n)} kr`}
function renderProtein(){const wrap=$('#protein-options');wrap.replaceChildren(...proteins.map(p=>{const b=document.createElement('button');b.className='chip'+(selected.has(p)?' selected':'');b.textContent=labels[p];b.addEventListener('click',()=>{if(p==='allt')selected=new Set(['allt']);else{selected.delete('allt');selected.has(p)?selected.delete(p):selected.add(p);if(!selected.size)selected.add('allt')}renderProtein()});return b}))}
function chooseMenu(days,people,budget){const allowed=selected.has('allt')?recipes:recipes.filter(r=>selected.has(r.protein));const target=budget/people;const pool=allowed.filter(r=>r.price<=target/days*1.3);const candidates=pool.length>=days?pool:allowed;const chosen=[],available=[...candidates];let spent=0;for(let i=0;i<days;i++){const desired=(target-spent)/(days-i);const under=available.filter(r=>r.price<=desired);const options=under.length?under:available;const nearest=[...options].sort((a,b)=>Math.abs(a.price-desired)-Math.abs(b.price-desired)).slice(0,Math.min(8,options.length));const next=nearest[Math.floor(Math.random()*nearest.length)];available.splice(available.indexOf(next),1);chosen.push(next);spent+=next.price}return chosen}
function build(){const budget=Number($('#budget').value)||0,days=Number($('#days').value),people=Number($('#people').value);localStorage.setItem('middagbudget',JSON.stringify({budget,days,people}));current=chooseMenu(days,people,budget);const total=current.reduce((sum,r)=>sum+r.price*people,0);$('#total').textContent=kronor(total);$('#remaining').textContent=kronor(Math.max(0,budget-total));$('#menu').replaceChildren(...current.map(r=>{const el=$('#meal-template').content.firstElementChild.cloneNode(true);el.querySelector('.meal-icon').textContent=r.icon;el.querySelector('h3').textContent=r.name;el.querySelector('p').textContent=`${r.time} · ${labels[r.protein]} · ca ${kronor(r.price)} / portion`;el.querySelector('strong').textContent=kronor(r.price*people);el.addEventListener('click',()=>showRecipe(r,people));return el;}));$('#shopping').replaceChildren();$('#add-all').hidden=false;$('#list-intro').hidden=false;$('#reset-checks').hidden=true;$('#results').hidden=false}
function addAll(){const list=[...new Set(current.flatMap(r=>r.ingredients))].sort((a,b)=>a.localeCompare(b,'sv'));$('#shopping').replaceChildren(...list.map(x=>{const li=document.createElement('li'),box=document.createElement('input');box.type='checkbox';box.setAttribute('aria-label',x);li.append(box,document.createTextNode(x));return li;}));$('#add-all').hidden=true;$('#list-intro').hidden=true;$('#reset-checks').hidden=false}
function scaled(x,people){return x.replace(/^(\d+(?:,\d+)?)(\s+.*)$/,(_,n,rest)=>`${(Number(n.replace(',','.'))*people/2).toLocaleString('sv-SE',{maximumFractionDigits:1})}${rest}`)}
function showRecipe(r,people){const tips={fisk:'Undvik att översteka fisken – den är klar när den lätt delar sig i skivor.',kyckling:'Kycklingen är klar när köttsaften är klar och innertemperaturen är 72°.',nöt:'Låt större köttbitar vila några minuter före servering så blir de saftigare.',fläsk:'Låt köttet vila under folie medan du gör klart tillbehören.',vegetariskt:'Smaka av ordentligt med salt, peppar och lite citron eller vinäger för mer djup.'};$('#recipe-content').innerHTML=`<p class="recipe-hero">${r.icon}</p><h2>${r.name}</h2><p class="recipe-meta">${r.time} · ${labels[r.protein]} · för ${people} personer</p><h3>Du behöver</h3><ul>${r.ingredients.map(x=>`<li>${scaled(x,people)}</li>`).join('')}</ul><h3>Gör så här</h3><ol>${r.steps.map(x=>`<li>${x}</li>`).join('')}</ol><aside class="recipe-tip"><strong>Tips från köket</strong><span>${tips[r.protein]}</span></aside>`;$('#recipe-dialog').showModal()}
$('#generate').addEventListener('click',build);$('#add-all').addEventListener('click',addAll);$('#reset-checks').addEventListener('click',()=>document.querySelectorAll('#shopping input').forEach(x=>x.checked=false));$('#close-recipe').addEventListener('click',()=>$('#recipe-dialog').close());$('#share').addEventListener('click',async()=>{const text='Veckomeny:\n'+current.map(r=>`• ${r.name}`).join('\n');if(navigator.share)await navigator.share({title:'Mudget',text});else await navigator.clipboard.writeText(text)});const saved=JSON.parse(localStorage.getItem('middagbudget')||'null');if(saved){$('#budget').value=saved.budget;$('#days').value=saved.days;$('#people').value=saved.people}renderProtein();if('serviceWorker'in navigator)navigator.serviceWorker.register('sw.js');

const avoidChoices={skaldjur:['räk','skaldjur'],svamp:['svamp','champinjon'],laktos:['grädde','ost','parmesan','feta','halloumi','burrata','yoghurt','crème']};
const pantryChoices=['ris','pasta','potatis','olja','kryddor','salt & peppar'];let avoided=new Set(JSON.parse(localStorage.getItem('mudget-avoid')||'[]')),pantryItems=new Set(JSON.parse(localStorage.getItem('mudget-pantry')||'[]')),favorites=new Set(JSON.parse(localStorage.getItem('mudget-favorites')||'[]'));let activeRecipe=null,activePeople=2,lastConfig=null;
function saveSet(key,set){localStorage.setItem(key,JSON.stringify([...set]))}
function renderToggleChoices(target,choices,set,onChange){const el=$(target);el.replaceChildren(...Object.keys(choices).map(key=>{const b=document.createElement('button');b.type='button';b.className='chip'+(set.has(key)?' selected':'');b.textContent=key[0].toUpperCase()+key.slice(1);b.onclick=()=>{set.has(key)?set.delete(key):set.add(key);onChange();renderToggleChoices(target,choices,set,onChange)};return b}))}
function renderPantry(){const choices=Object.fromEntries(pantryChoices.map(x=>[x,x]));renderToggleChoices('#pantry-options',choices,pantryItems,()=>{saveSet('mudget-pantry',pantryItems);if($('#shopping').children.length)addAllEnhanced()})}
function recipeAllowed(r){const text=`${r.name} ${r.ingredients.join(' ')}`.toLowerCase();return ![...avoided].some(key=>avoidChoices[key].some(word=>text.includes(word)))}
function pickClose(candidates,count,people,budget){const available=[...candidates],picked=[];let spent=0;for(let i=0;i<count&&available.length;i++){const desired=(budget/people-spent)/(count-i);const under=available.filter(r=>r.price<=desired);const options=under.length?under:available;const nearest=[...options].sort((a,b)=>Math.abs(a.price-desired)-Math.abs(b.price-desired)).slice(0,Math.min(8,options.length));const next=nearest[Math.floor(Math.random()*nearest.length)];available.splice(available.indexOf(next),1);picked.push(next);spent+=next.price}return picked}
function enhancedChoices(days,people,budget){const allowed=(selected.has('allt')?recipes:recipes.filter(r=>selected.has(r.protein))).filter(recipeAllowed);const vegWanted=Math.min(Number($('#vegetarian-min').value),days);const veg=pickClose(allowed.filter(r=>r.protein==='vegetariskt'),vegWanted,people,budget*vegWanted/days);const rest=pickClose(allowed.filter(r=>!veg.includes(r)),days-veg.length,people,budget-veg.reduce((sum,r)=>sum+r.price*people,0));return [...veg,...rest].sort(()=>Math.random()-.5)}
function renderMenu(){const budget=lastConfig.budget,people=lastConfig.people,total=current.reduce((sum,r)=>sum+r.price*people,0);$('#total').textContent=kronor(total);$('#remaining').textContent=kronor(Math.max(0,budget-total));$('#menu').replaceChildren(...current.map((r,index)=>{const el=$('#meal-template').content.firstElementChild.cloneNode(true);el.querySelector('.meal-icon').textContent=r.icon;el.querySelector('h3').textContent=r.name;el.querySelector('p').textContent=`${r.time} · ${labels[r.protein]} · ca ${kronor(r.price)} / portion`;el.querySelector('strong').textContent=kronor(r.price*people);el.querySelector('.meal-main').addEventListener('click',()=>showDetailedRecipe(r,people));el.querySelector('.swap-icon').addEventListener('click',()=>swapMealAt(index));return el;}));$('#shopping').replaceChildren();$('#add-all').hidden=false;$('#list-intro').hidden=false;$('#reset-checks').hidden=true;$('.list-actions').hidden=true;$('#results').hidden=false}
function smoothScrollTo(top,duration=520){const start=window.scrollY,distance=top-start,startTime=performance.now();const step=now=>{const progress=Math.min(1,(now-startTime)/duration),ease=1-Math.pow(1-progress,3);window.scrollTo(0,start+distance*ease);if(progress<1)requestAnimationFrame(step)};requestAnimationFrame(step)}
function generateEnhanced(){const budget=Number($('#budget').value)||0,days=Number($('#days').value),people=Number($('#people').value);lastConfig={budget,days,people};current=enhancedChoices(days,people,budget);$('#cost-label').textContent='BERÄKNAD KOSTNAD';$('#price-attribution').hidden=true;renderMenu();requestAnimationFrame(()=>requestAnimationFrame(()=>{const target=$('#results');smoothScrollTo(Math.max(0,target.getBoundingClientRect().top+window.scrollY-12))}))}
function showDetailedRecipe(r,people){activeRecipe=r;activePeople=people;const tips={fisk:'Undvik att översteka fisken – den är klar när den lätt delar sig i skivor.',kyckling:'Kycklingen är klar när köttsaften är klar och innertemperaturen är 72°.',nöt:'Låt större köttbitar vila några minuter före servering så blir de saftigare.',fläsk:'Låt köttet vila under folie medan du gör klart tillbehören.',vegetariskt:'Smaka av med salt, peppar och lite citron eller vinäger för mer djup.'};$('#recipe-content').innerHTML=`<p class="recipe-hero">${r.icon}</p><h2>${r.name}</h2><p class="recipe-meta">${r.time} · ${labels[r.protein]} · för ${people} personer</p><h3>Du behöver</h3><ul>${r.ingredients.map(x=>`<li>${scaled(x,people)}</li>`).join('')}</ul><h3>Gör så här</h3><ol>${r.steps.map(x=>`<li>${x}</li>`).join('')}</ol><aside class="recipe-tip"><strong>Tips från köket</strong><span>${tips[r.protein]}</span></aside><button id="swap-meal" class="secondary">Byt den här middagen</button><button id="favorite-meal" class="text-button recipe-favorite">${favorites.has(r.name)?'★ Sparad favorit':'☆ Spara som favorit'}</button>`;$('#swap-meal').onclick=swapActiveMeal;$('#favorite-meal').onclick=()=>{favorites.has(r.name)?favorites.delete(r.name):favorites.add(r.name);saveSet('mudget-favorites',favorites);showDetailedRecipe(r,people)};$('#recipe-dialog').showModal()}
function swapMealAt(index){const previous=current[index],excluded=new Set(current);const candidates=(selected.has('allt')?recipes:recipes.filter(r=>selected.has(r.protein))).filter(r=>recipeAllowed(r)&&!excluded.has(r));const replacement=pickClose(candidates,1,lastConfig.people,previous.price*lastConfig.people)[0];if(replacement){current[index]=replacement;renderMenu();setTimeout(updateIndexedPrices,0)}}
function swapActiveMeal(){const index=current.indexOf(activeRecipe);$('#recipe-dialog').close();swapMealAt(index)}
function parsedIngredient(text){const m=text.match(/^(.+?)\s+(\d+(?:,\d+)?)\s+(g|dl|st|fp)$/i);return m?{name:m[1],amount:Number(m[2].replace(',','.')),unit:m[3]}:{name:text,amount:1,unit:''}}
function addAllEnhanced(){if(!lastConfig)return;const sums=new Map;current.flatMap(r=>r.ingredients.map(x=>scaled(x,lastConfig.people))).map(parsedIngredient).forEach(item=>{const key=`${item.name.toLowerCase()}|${item.unit}`;const prior=sums.get(key)||{...item};prior.amount+=sums.has(key)?item.amount:0;sums.set(key,prior)});const rows=[...sums.values()].filter(item=>!pantryItems.has(item.name.toLowerCase())).sort((a,b)=>a.name.localeCompare(b.name,'sv'));$('#shopping').replaceChildren(...rows.map(item=>{const text=item.unit?`${item.name} ${item.amount.toLocaleString('sv-SE',{maximumFractionDigits:1})} ${item.unit}`:item.name;const li=document.createElement('li'),box=document.createElement('input');box.type='checkbox';box.setAttribute('aria-label',text);li.append(box,document.createTextNode(text));return li;}));$('#add-all').hidden=true;$('#list-intro').hidden=true;$('#reset-checks').hidden=false;$('.list-actions').hidden=false}
renderToggleChoices('#exclude-options',avoidChoices,avoided,()=>saveSet('mudget-avoid',avoided));renderPantry();$('#generate').addEventListener('click',generateEnhanced);$('#add-all').addEventListener('click',addAllEnhanced);$('#share-list').addEventListener('click',async()=>{const text='Mudget – inköpslista\n'+[...$('#shopping li')].map(x=>`• ${x.textContent}`).join('\n');if(navigator.share)await navigator.share({title:'Mudget – inköpslista',text});else await navigator.clipboard.writeText(text)});$('#clear-pantry').addEventListener('click',()=>{pantryItems.clear();saveSet('mudget-pantry',pantryItems);renderPantry();addAllEnhanced()});
const chainLogos={ica:'https://commons.wikimedia.org/wiki/Special:FilePath/ICA_logo.svg',coop:'https://commons.wikimedia.org/wiki/Special:FilePath/Coop_logo.svg',lidl:'https://commons.wikimedia.org/wiki/Special:FilePath/Lidl-Logo.svg'};let selectedChain=localStorage.getItem('mudget-chain')||'ica';function renderChains(){const options=[['ica','ICA'],['ica-maxi','ICA Maxi'],['coop','Coop'],['lidl','Lidl']];const wrap=$('#chain-options');wrap.replaceChildren(...options.map(([id,label])=>{const button=document.createElement('button');button.type='button';button.className='chain-option'+(selectedChain===id?' selected':'');button.setAttribute('aria-pressed',selectedChain===id);button.setAttribute('aria-label',label);if(id==='ica-maxi')button.innerHTML=`<span class="maxi-mark"><img src="${chainLogos.ica}" alt="" /><span>MAXI</span></span>`;else button.innerHTML=`<img src="${chainLogos[id]}" alt="${label}" />`;button.onclick=()=>{selectedChain=id;localStorage.setItem('mudget-chain',id);renderChains()};return button}))}renderChains();
const PRIMAT_KEY='primat_pk_VdC84Z7ha0relv1jpdX9eRCgE7UAZTbCu9XdDqtoWnA';let selectedStore=JSON.parse(localStorage.getItem('mudget-store')||'null');let resolvedStores=[];
async function primat(path){const response=await fetch(`https://primat.nu/api/v3${path}`,{headers:{Authorization:`Bearer ${PRIMAT_KEY}`}});const body=await response.json();if(!response.ok)throw new Error(body.error?.message||'Kunde inte hämta prisdata.');return body}
function chainForLookup(){return selectedChain==='ica-maxi'?'ica':selectedChain}
function visibleStores(stores){return stores.filter(store=>{if(store.chain!==chainForLookup())return false;const maxi=/maxi/i.test(store.name||'');return selectedChain==='ica-maxi'?maxi:!maxi})}
async function findStores(){const place=$('#store-place').value.trim();if(!place){$('#store-status').textContent='Skriv en ort eller ett postnummer först.';return}$('#store-status').textContent='Söker efter butiker…';try{const result=await primat(`/stores/resolve?place=${encodeURIComponent(place)}`);resolvedStores=visibleStores(result.stores||[]);const select=$('#store-select');select.replaceChildren(...resolvedStores.map(store=>{const option=document.createElement('option');option.value=store.key||`${store.chain}:${store.store_id}`;option.textContent=`${store.name}${store.city?` – ${store.city}`:''}${store.km!=null?` (${store.km} km)`:''}`;return option}));if(!resolvedStores.length){select.hidden=true;$('#store-status').textContent='Ingen butik med tillgänglig prisdata hittades för den kedjan där.';return}select.hidden=false;select.value=selectedStore?.key===select.value?selectedStore.key:select.options[0].value;selectStore();$('#store-status').textContent='Välj butik nedan. Aktuella priser hämtas när du föreslår middagar.'}catch(error){$('#store-status').textContent=error.message}}
function selectStore(){const key=$('#store-select').value;selectedStore=resolvedStores.find(store=>(store.key||`${store.chain}:${store.store_id}`)===key)||null;if(selectedStore){selectedStore.key=key;localStorage.setItem('mudget-store',JSON.stringify(selectedStore));if(current.length)updateIndexedPrices()}}
function liveSearchTerms(ingredient){const raw=parsedIngredient(ingredient).name.toLowerCase();if(/^(salt|peppar|olja|kryddor|buljong|smör|vinäger)$/.test(raw))return [];const mappings=[[/spaghetti|makaroner|risoni/,'pasta'],[/äggnudlar/,'äggnudlar'],[/pasta/,'pasta'],[/lax/,'laxfilé'],[/torsk/,'torskfilé'],[/sej/,'sejfilé'],[/kolja/,'koljafilé'],[/vit fisk|havskatt|rödspätta/,'fiskfilé'],[/räk|skaldjur/,'räkor'],[/kyckling/,'kycklingfilé'],[/nötfärs|färsbiff|köttbull/,'nötfärs'],[/entrecôte|ryggbiff|lövbiff|biffstriml/,'nötkött'],[/högrev/,'högrev'],[/fläskfärs/,'fläskfärs'],[/fläskfilé|fläskytterfilé/,'fläskfilé'],[/chorizo|salsiccia|falukorv/,'korv'],[/potatis/,'potatis'],[/sötpotatis/,'sötpotatis'],[/risottoris/,'risottoris'],[/ris/,'ris'],[/matlagningsgrädde|crème fraiche/,'matlagningsgrädde'],[/parmesan/,'parmesan'],[/fetaost/,'fetaost'],[/halloumi/,'halloumi'],[/burrata/,'burrata'],[/riven ost|cheddar|mozzarella/,'riven ost'],[/krossade tomater|tomatsås/,'krossade tomater'],[/tortillabröd/,'tortillabröd'],[/broccoli/,'broccoli'],[/spenat/,'spenat'],[/champinjon|svamp/,'champinjoner'],[/paprika/,'paprika'],[/morot/,'morötter'],[/gul lök/,'gul lök'],[/avokado/,'avokado'],[/kikärter/,'kikärter'],[/bönor/,'bönor'],[/majs/,'majs'],[/yoghurt/,'yoghurt']];const mapped=mappings.find(([pattern])=>pattern.test(raw))?.[1];return [...new Set([mapped,raw].filter(Boolean))]}
async function liveProductPrice(ingredient,storeKey){for(const term of liveSearchTerms(ingredient)){const data=await primat(`/products?q=${encodeURIComponent(term)}&stores=${encodeURIComponent(storeKey)}&limit=5`);const product=(data.data||[]).find(item=>item.available&&(item.prices?.effective??item.prices?.regular)!=null);const price=product?.prices?.effective??product?.prices?.regular;if(typeof price==='number')return price}return null}
async function updateLiveCost(){if(!selectedStore||!current.length)return;const storeKey=selectedStore.key||`${selectedStore.chain}:${selectedStore.store_id}`;const items=[...new Set(current.flatMap(recipe=>recipe.ingredients))].filter(item=>liveSearchTerms(item).length);$('#store-status').textContent='Hämtar aktuella priser för veckomenyn…';try{const results=await Promise.all(items.map(item=>liveProductPrice(item,storeKey)));const matched=results.filter(price=>typeof price==='number');if(!matched.length)throw new Error('Kunde inte matcha varorna mot den valda butiken.');const estimated=current.reduce((sum,recipe)=>sum+recipe.price*lastConfig.people,0);if(matched.length===items.length){const total=matched.reduce((sum,price)=>sum+price,0);$('#total').textContent=kronor(total);$('#cost-label').textContent='AKTUELL BUTIKSKORG'}else{$('#total').textContent=kronor(estimated);$('#cost-label').textContent=`BERÄKNAD KOSTNAD · ${matched.length}/${items.length} LIVEPRISER`}$('#remaining').textContent=kronor(Math.max(0,lastConfig.budget-Number($('#total').textContent.replace(/[^0-9]/g,''))));$('#price-attribution').hidden=false;$('#store-status').textContent=`Prisdata hittades för ${matched.length} av ${items.length} inköpsvaror hos ${selectedStore.name}. Vi visar uppskattad totalsumma tills alla varor är exakt matchade.`}catch(error){$('#store-status').textContent=`Prisuppdatering misslyckades: ${error.message}`}}
$('#find-store').addEventListener('click',findStores);$('#store-select').addEventListener('change',selectStore);
$('#reset-checks').addEventListener('click',()=>{$('#shopping').replaceChildren();$('#add-all').hidden=false;$('#list-intro').hidden=false;$('#reset-checks').hidden=true;$('.list-actions').hidden=true});
const INGREDIENT_INDEX=[
 ['pasta',/spaghetti|makaron|risoni|gnocchi|lasagneplatt|pasta/,'pasta'],['nudlar',/nudlar/,'äggnudlar'],['risottoris',/risottoris/,'risottoris'],['ris',/\bris\b/,'ris'],['potatis',/sötpotatis/,'sötpotatis'],['potatis',/potatis/,'potatis'],['lax',/lax/,'laxfilé'],['torsk',/torsk/,'torskfilé'],['sej',/sej/,'sejfilé'],['kolja',/kolja/,'koljafilé'],['fiskfilé',/fiskfilé|vit fisk|havskatt|rödspätta/,'fiskfilé'],['räkor',/räk|skaldjur/,'räkor'],['tonfisk',/tonfisk/,'tonfisk'],['kyckling',/kyckling/,'kycklingfilé'],['nötfärs',/nötfärs|köttbull|färsbiff/,'nötfärs'],['nötkött',/entrecôte|ryggbiff|lövbiff|biffstriml/,'nötkött'],['högrev',/högrev/,'högrev'],['fläskfärs',/fläskfärs/,'fläskfärs'],['fläskfilé',/fläskfilé|fläskytterfilé/,'fläskfilé'],['korv',/salsiccia|chorizo|falukorv|kycklingkorv/,'korv'],['kassler',/kassler/,'kassler'],['pulled-pork',/pulled pork/,'pulled pork'],['grädde',/matlagningsgrädde|crème fraiche/,'matlagningsgrädde'],['yoghurt',/yoghurt/,'yoghurt'],['parmesan',/parmesan/,'parmesan'],['fetaost',/fetaost|chèvre/,'fetaost'],['halloumi',/halloumi/,'halloumi'],['burrata',/burrata/,'burrata'],['ost',/riven ost|cheddar|mozzarella/,'riven ost'],['tomater',/krossade tomater|tomatsås/,'krossade tomater'],['tortilla',/tortillabröd/,'tortillabröd'],['broccoli',/broccoli/,'broccoli'],['spenat',/spenat/,'spenat'],['svamp',/champinjon|svamp/,'champinjoner'],['paprika',/paprika/,'paprika'],['morötter',/morot/,'morötter'],['lök',/gul lök/,'gul lök'],['avokado',/avokado/,'avokado'],['kikärter',/kikärter/,'kikärter'],['bönor',/bönor/,'bönor'],['majs',/majs/,'majs'],['citron',/citron|lime/,'citron'],['sallad',/sallad/,'sallad'],['ägg',/\bägg\b/,'ägg'],['mjölk',/mjölk/,'mjölk']
];
let indexedPrices=new Map;let productCache=JSON.parse(localStorage.getItem('mudget-product-cache')||'{}');
function indexedIngredient(raw){const clean=parsedIngredient(raw),name=clean.name.toLowerCase();if(/^(salt|peppar|olja|kryddor|buljong|smör|vinäger|dill|saffran|honung|soja|pesto|tomatpuré|tacokrydda)$/.test(name))return null;const found=INGREDIENT_INDEX.find(([,pattern])=>pattern.test(name));return {raw,name,amount:clean.amount,unit:clean.unit,id:found?.[0]||name,query:found?.[2]||name}}
function productScore(product,spec){const title=`${product.name||''} ${product.brand||''}`.toLowerCase();let score=title.includes(spec.query)?40:0;for(const word of spec.query.split(/\s+/))if(title.includes(word))score+=8;if(product.amount&&spec.amount&&['g','ml'].includes(String(product.unit||'').toLowerCase()))score-=Math.abs(Number(product.amount)-spec.amount)/Math.max(spec.amount,1)*6;if(product.available)score+=5;return score}
async function resolveIndexedPrice(raw,storeKey){const spec=indexedIngredient(raw);if(!spec)return null;const cacheKey=`${storeKey}|${spec.id}|${spec.amount}${spec.unit}`;const today=new Date().toISOString().slice(0,10);if(productCache[cacheKey]?.date===today)return productCache[cacheKey];const data=await primat(`/products?q=${encodeURIComponent(spec.query)}&stores=${encodeURIComponent(storeKey)}&limit=25`);const product=[...(data.data||[])].filter(item=>item.available&&(item.prices?.effective??item.prices?.regular)!=null).sort((a,b)=>productScore(b,spec)-productScore(a,spec))[0];if(!product)return null;const result={date:today,price:product.prices?.effective??product.prices?.regular,name:product.name,package:product.package||'',query:spec.query};productCache[cacheKey]=result;localStorage.setItem('mudget-product-cache',JSON.stringify(productCache));return result}
async function updateIndexedPrices(){if(!selectedStore||!current.length)return;const storeKey=selectedStore.key||`${selectedStore.chain}:${selectedStore.store_id}`;const ingredients=[...new Set(current.flatMap(recipe=>recipe.ingredients))].filter(indexedIngredient);$('#store-status').textContent='Hämtar butikspriser för ingredienserna…';try{const results=await Promise.all(ingredients.map(item=>resolveIndexedPrice(item,storeKey)));indexedPrices=new Map(ingredients.map((item,index)=>[item,results[index]]));const matched=results.filter(Boolean).length;$('#cost-label').textContent=`BERÄKNAD KOSTNAD · BUTIKSPRISER ${matched}/${ingredients.length}`;$('#price-attribution').hidden=false;$('#store-status').textContent=`Butikspriser hittades för ${matched} av ${ingredients.length} ingredienser hos ${selectedStore.name}. Exakta varunamn visas i inköpslistan när du lägger till den.`}catch(error){$('#store-status').textContent=`Prisuppdatering misslyckades: ${error.message}`}}
async function hydrateShoppingPrices(){if(!selectedStore||!$('#shopping').children.length)return;const storeKey=selectedStore.key||`${selectedStore.chain}:${selectedStore.store_id}`;const rows=[...$('#shopping li')];const results=await Promise.all(rows.map(row=>resolveIndexedPrice(row.textContent,storeKey).catch(()=>null)));let total=0,matched=0;rows.forEach((row,index)=>{const result=results[index];if(!result)return;matched++;total+=result.price;const detail=document.createElement('small');detail.className='item-price';detail.textContent=`ca ${kronor(result.price)} · ${result.name}${result.package?` (${result.package})`:''}`;row.append(detail)});if(matched){$('#store-status').textContent=`Butikspriser på ${matched}/${rows.length} inköpsvaror · matchad del av korgen: ${kronor(total)}.`;$('#price-attribution').hidden=false}}
$('#generate').addEventListener('click',()=>setTimeout(updateIndexedPrices,0));$('#add-all').addEventListener('click',()=>setTimeout(hydrateShoppingPrices,0));
